name: CI

on: [push]

jobs:
  build:
    name: CI

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: mvn compile --file pom.xml
    - name: Test
      run: mvn test --file pom.xml
    - name: SonarCloud
      run: mvn verify sonar:sonar -Dsonar.projectKey=LevelFourAB_graphql-binding -Dsonar.organization=levelfourab -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Package
      run: mvn -Prelease -DskipTests package --file pom.xml
